trigger:
  branches:
    include:
      - main

parameters:
  - name: version
    type: string
    default: 'latest'
  - name: region
    type: string
    default: 'westeurope'
  - name: containerName
    type: string
    default: 'python-app-container-ado'

variables:
  ACR_NAME: 'containersr'
  IMAGE_NAME: 'python-app-ado'
  RESOURCE_GROUP: 'Container'
  DNS_LABEL: '$(IMAGE_NAME)-$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureConnectionContainer'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging into ACR..."
      az acr login --name $ACR_NAME

      echo "Building Docker image..."
      docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ parameters.version }} .

      echo "Pushing Docker image to ACR..."
      docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ parameters.version }}

      echo "Getting ACR credentials..."
      ACR_USERNAME=$(az acr credential show --name $ACR_NAME --query "username" -o tsv)
      ACR_PASSWORD=$(az acr credential show --name $ACR_NAME --query "passwords[0].value" -o tsv)

      echo "Setting DNS label..."
      DNS_LABEL=${IMAGE_NAME}-${{ parameters.region }}-${BUILD_BUILDID}

      echo "Deploying to Azure Container Instance..."
      az container create \
        --resource-group $RESOURCE_GROUP \
        --name ${{ parameters.containerName }} \
        --image $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ parameters.version }} \
        --cpu 1 \
        --memory 1 \
        --location ${{ parameters.region }} \
        --dns-name-label $DNS_LABEL \
        --registry-login-server $ACR_NAME.azurecr.io \
        --registry-username $ACR_USERNAME \
        --registry-password $ACR_PASSWORD
